project_id = "xqzlejcvvtjdrabofrxs"

[global.env]
NYLAS_CLIENT_ID = "env"
NYLAS_CLIENT_SECRET = "env"
NYLAS_WEBHOOK_SECRET = "env"

[functions.handle-nylas-webhook]
verify_jwt = false
verify_webhook = true
max_instances = 30
timeout_ms = 10000
rate_limit = 100
concurrency = 50

[functions.handle-message-webhook]
verify_jwt = false
verify_webhook = false