project_id = "xqzlejcvvtjdrabofrxs"

[global.env]
NYLAS_CLIENT_ID = "env"
NYLAS_CLIENT_SECRET = "env"
NYLAS_WEBHOOK_SECRET = "env"

[functions.handle-nylas-webhook]
verify_jwt = false
verify_webhook = false
# Keep function warm by increasing max instances and reducing timeout
max_instances = 5
timeout_ms = 10000

[functions.handle-message-webhook]
verify_jwt = false
verify_webhook = false