
project_id = "xqzlejcvvtjdrabofrxs"

[global.env]
NYLAS_CLIENT_ID = "env(NYLAS_CLIENT_ID)"
NYLAS_CLIENT_SECRET = "env(NYLAS_CLIENT_SECRET)"
NYLAS_WEBHOOK_SECRET = "env(NYLAS_WEBHOOK_SECRET)"
NYLAS_PROD_CLIENT_ID = "env(NYLAS_PROD_CLIENT_ID)"
NYLAS_PROD_CLIENT_SECRET = "env(NYLAS_PROD_CLIENT_SECRET)"
NYLAS_PROD_WEBHOOK_SECRET = "env(NYLAS_PROD_WEBHOOK_SECRET)"

[[functions]]
name = "exchange-nylas-token"
verify_jwt = true

[[functions]]
name = "get-nylas-auth-url"
verify_jwt = true

[[functions]]
name = "get-organization-data"
verify_jwt = true

[[functions]]
name = "get-recording-media"
verify_jwt = true

[[functions]]
name = "handle-nylas-webhook"
verify_jwt = false

[[functions]]
name = "handle-mux-webhook"
verify_jwt = false

[[functions]]
name = "kick-notetaker"
verify_jwt = true

[[functions]]
name = "process-notetaker-queue"
verify_jwt = false  # Explicitly disable JWT verification for cron job access

[[functions]]
name = "queue-event-recording"
verify_jwt = true

[[functions]]
name = "send-notetaker"
verify_jwt = true

[[functions]]
name = "send-organization-invite"
verify_jwt = true

[[functions]]
name = "send-recording-email"
verify_jwt = true

[[functions]]
name = "send-recording-ready-email"
verify_jwt = true

[[functions]]
name = "sync-nylas-events"
verify_jwt = true

[[functions]]
name = "incremental-cant-trust-webhooks"
verify_jwt = true

[[functions]]
name = "send-grant-expired-email"
verify_jwt = true
