project_id = "xqzlejcvvtjdrabofrxs"

[global.env]
NYLAS_CLIENT_ID = "env"
NYLAS_CLIENT_SECRET = "env"
NYLAS_WEBHOOK_SECRET = "env"

[functions.handle-nylas-webhook]
verify_jwt = false
verify_webhook = false
# Increase max instances to handle concurrent webhooks
max_instances = 10
# Reduce timeout to prevent function from hanging
timeout_ms = 5000
# Add rate limiting to prevent throttling
rate_limit = 100
# Add concurrency to handle multiple webhooks simultaneously
concurrency = 50

[functions.handle-message-webhook]
verify_jwt = false
verify_webhook = false