project_id = "xqzlejcvvtjdrabofrxs"

[global.env]
NYLAS_CLIENT_ID = "env"
NYLAS_CLIENT_SECRET = "env"
NYLAS_WEBHOOK_SECRET = "env"

[functions.handle-nylas-webhook]
verify_jwt = false
verify_webhook = false

[functions.handle-message-webhook]
verify_jwt = false
verify_webhook = false